project:
  type: website
  output-dir: "../docs"
  render:
    - "*.qmd"
    - "!dev.qmd"

website:
  title: "Mitan"
  favicon: assets/IconMitan.png
  open-graph: true
  search: 
    location: navbar
    type: textbox 
  navbar:
    title: false
    logo: assets/LogoMitanRect.png
    search: true
    left:
      - href: index.qmd
        text: Accueil
      - href: communes.qmd
        text: Communes Disponibles
      - href: foret-score.qmd
        text: Le Forêt-Score
  page-footer: |
    [Plus d'informations sur les données](./details.html) |
    [Mentions légales](./mentions.html)

format:
  html:
    include-in-header:
      - text: <script>window.onload = function() {document.getElementById('autocomplete-0-input').placeholder = 'Commune';};</script>
    theme: 
      - cosmo
      - custom.scss
    toc: false
    minify: true
  
resources:
  - "communes_results/*"
  - CNAME
  
language: 
  search-text-placeholder: "Rechercher une commune"

