project:
  type: website
  output-dir: "../docs"
  render:
    - "*.qmd"
    - "!dev.qmd"

website:
  title: "Mitan"
  favicon: assets/IconMitan.png
  search: 
    location: navbar
    type: textbox 
  navbar:
    title: false
    logo: assets/LogoMitanRect.png
    search: true
    left:
      - href: index.qmd
        text: Accueil
      - href: communes.qmd
        text: Communes
      - href: details.qmd
        text: Détails
format:
  html:
    include-in-header:
      - text: <script>window.onload = function() {document.getElementById('autocomplete-0-input').placeholder = 'Commune';};</script>
    theme: 
      - cosmo
      - custom.scss
    toc: false
    minify: true
  
resources:
  - "communes_results/*"

language: 
  search-text-placeholder: "Rechercher une commune"

