project:
  type: website
  output-dir: "../docs"

website:
  title: "Mitan"
  favicon: assets/IconMitan.png
  search: 
    location: navbar
    type: textbox 
  navbar:
    title: false
    logo: assets/LogoMitanRect.png
    search: true
    left:
      - href: index.qmd
        text: Accueil
      - about.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: false
    minify: true

language: 
  search-text-placeholder: "Rechercher une commune"

