project:
  type: website
  output-dir: "../docs"

website:
  title: "Mitan"
  search: 
    location: navbar
    type: textbox 
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd

language: 
  search-text-placeholder: "Rechercher une commune"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



