project:
  type: website
  output-dir: "../docs"
  render:
    - "*.qmd"
    - "!dev.qmd"
  preview:
    port: 4242
    browser: false

website:
  title: "Mitan"
  description: "Mitan est plateforme dédiée à l'exploration et au suivi du patrimoine forestier des communes françaises."
  favicon: assets/IconMitan.png
  open-graph: true
  navbar:
    title: false
    logo: assets/LogoMitanRect.png
    search: false
    left:
      - href: index.qmd
        text: Accueil
      - href: communes.qmd
        text: Chercher une Commune
      - href: foret-score.qmd
        text: Le Forêt-Score
      - menu:
          - text: Détails sur les données
            href:  details.html
          - text: Mentions légales
            href:  mentions.html
    collapse: true # Enable collapsible navbar

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: false
    minify: true
  
resources:
  - CNAME
  - libs/*
