project:
  type: website
  output-dir: "../docs"
  render:
    - "*.qmd"
    - "!dev.qmd"

website:
  title: "Mitan"
  favicon: assets/IconMitan.png
  open-graph: true
  navbar:
    title: false
    logo: assets/LogoMitanRect.png
    search: true
    left:
      - href: index.qmd
        text: Accueil
      - href: communes.qmd
        text: Chercher une Commune
      - href: foret-score.qmd
        text: Le Forêt-Score
  page-footer: |
    Ce site est optimisé pour une navigation sur ordinateur. Dernière mise-à-jour : mars 2025 |
    [Détails sur les données](./details.html) |
    [Mentions légales](./mentions.html)

format:
  html:
    include-in-header:
      - text: <script>window.onload = function() {document.getElementById('autocomplete-0-input').placeholder = 'Commune';};</script>
    theme: 
      - cosmo
      - custom.scss
    toc: false
    minify: true
    grid:
      margin-width: 100px
      body-width: 800px
  
resources:
  - CNAME
  - "comm_list.csv"
  - "a-com2022.json"

language: 
  search-text-placeholder: "Rechercher une commune"

