---
title: "Détails"
---

Comme pour toutes les données, il est important de connaître leurs limites afin de mieux comprendre ce qu'elles peuvent vraiment nous révéler.

### Limites de la classification des types de forêts

La classification des types de forêts (et leur localisation) provient de la base de données BDForêt® de l'IGN. Celle-ci est générée via un processus semi-automatisé, qui, bien que fiable, comporte quelques imprécisions, notamment :

-   BDForêt repose sur des relevés et des informations générées sur plusieurs années. Or, les forêts évoluent rapidement sous l’effet des interventions humaines (exploitation forestière, urbanisation) ou naturelles (tempêtes, incendies). Cela signifie que les informations fournies peuvent ne pas toujours refléter la situation actuelle sur le terrain.

-   La classification des types de forêts peut manquer de précision dans certaines zones. Par exemple, les types de forêts mixtes ou les forêts en transition peuvent être mal identifiés ou classés dans des catégories génériques. De plus, les petites parcelles forestières ou les forêts linéaires (comme les haies forestières) peuvent être mal représentées, voire omises.

### Limites de la détection des perturbations

La détection des perturbations majeures de l'écosystème forestier, même si elle repose sur un algorithme développé avec soin et passion en Limousin, présente aussi certaines limites :
  
  -   **Résolution temporelle et spatiale** : Avec une résolution de 10 mètres, Sentinel-2 permet de détecter des changements dans la végétation, mais peut manquer les petites coupes rases ou perturbations locales. Sa fréquence de passage (5 jours) peut également ne pas capter des événements temporaires ou survenus entre deux images.

-   **Conditions météorologiques** : Les images satellite peuvent être altérées par des nuages ou de la brume, surtout dans les zones humides. Même avec des corrections, certaines zones restent difficiles à observer précisément.

-   **Limites de l'indice NDVI** : Bien que bon indicateur de la végétation, le NDVI peine à distinguer les coupes rases d’autres perturbations (maladies, incendies). Dans les zones à végétation clairsemée ou feuillage persistant, il peut mal interpréter les variations.

-   **Réactivité aux changements subtils** : Le NDVI détecte bien les changements majeurs, mais est moins performant pour les coupes sélectives ou les perturbations progressives, qui peuvent être masquées par la régénération rapide de la végétation.

## Source des données

-   **Annotation des forêts**: [BDForêt® V2](https://geoservices.ign.fr/bdforet) sous [Licence ETALAB-Licence-Ouverte-v2.0](https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf)

-   **Altitudes**: [Service Géoplateforme de calcul altimétrique](https://geoservices.ign.fr/services-geoplateforme-altimetrie) sous [Licence ETALAB-Licence-Ouverte-v2.0](https://www.etalab.gouv.fr/wp-content/uploads/2017/04/ETALAB-Licence-Ouverte-v2.0.pdf)

-   **Données satellite**: Copernicus ([satellite Sentinel 2](https://sentiwiki.copernicus.eu/web/s2-mission)) obtenues par [Sentinel-Hub](https://www.sentinel-hub.com/), sous [Licence CC-BY-SA](https://creativecommons.org/licenses/by/4.0/deed.fr)

-   **Fond de carte**: ESRI

-   **Perturbations et calculs associés** - Algorithme maison sous [Licence CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/deed.fr)



## Comment est calculé le Forêt-Score?

### Composantes du score

Le score est basé sur deux variables :

__Taux de boisement__

Représente la proportion de la surface forestière par rapport à la surface totale d’un territoire.
Un taux élevé est généralement préférable, sauf en cas de surexploitation ou de monoculture excessive.

Échelle : 0 % (pas de forêt) à 100 % (territoire entièrement boisé).

__Taux de coupes rases__

Indique la part de la forêt soumise à des coupes rases (extraction totale du couvert forestier sur une surface donnée). Un faible taux est préférable pour la biodiversité et la résilience écologique.

Échelle : 0 % (aucune coupe rase) à 3 % et plus (forte pression).


Le score sera bientôt enrichi par ces deux variables :

__[A VENIR] Taux de coupes en espaces à haute valeur environnementale__

Mesure la part des zones forestières protégées (Natura 2000, réserves naturelles, ZNIEFF, etc.)
ayant subi des coupes rases.

Échelle : 0 % (aucune coupe en zone protégée) à 1 % et plus (forte pression).

__[A VENIR] Taux de monocultures__

Correspond à la proportion approximative de forêt plantée après exploitation ou déforestation.
Un bon équilibre entre régénération naturelle et plantation contrôlée est crucial.

Échelle : 0 % (pure forêt plantée mixte ou naturelle) à 100 % (monocultures).


### Calcul du Forêt Score

Chaque composante est évaluée sur une échelle de A (Excellent) à E (Critique).

__Le score final est le plus bas des scores obtenus à chaque composante.__

Exemple :
Si une forêt obtient A en boisement, B en coupes rases, C en espaces protégés, mais E en taux de plantation,
→ Le Forêt-Score sera E.

